version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Run Prime Check Script
          command: python prime.py 15  # You can replace 15 with any number you want to check

  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Run Tests
          command: python Test.py

workflows:
  build_and_test:
    jobs:
      - build
      - test
